# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personel', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'personels',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad:')),
                ('description', models.TextField(verbose_name='Yapılacak:')),
                ('title', models.CharField(max_length=200, null='true', verbose_name='Proje Adı 1:')),
                ('title2', models.CharField(max_length=200, null='true', verbose_name='Proje Adı 2:')),
                ('description2', models.TextField(verbose_name='Açıklama:')),
                ('pname', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='post.Personel', verbose_name='Personel Adı:')),
            ],
        ),
    ]
