# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-31 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180731_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pname',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='post.Personel', verbose_name='Personel:'),
        ),
    ]
